#!/usr/bin/env python3
"""build.py — regenerate the per-tool commands and the wiki from registry/tools.json.

Reads:   registry/tools.json, each tool's installed SKILL.md (via resolve.py), and the skill's
         references (phrases.md, collisions.md, stacking.md) for cross-links.
Writes:  commands/<tool>.md        one slash command per tool → /design-tools:<tool>
         wiki/tools/<tool>.md      one page per tool
         wiki/README.md            the index (vendors, tools by group, health)
Leaves:  commands/tool.md, commands/tools-list.md, commands/demo.md, wiki/vendors/*.md, wiki/LOADING.md — hand-written.

Generated files carry a GENERATED marker; stale generated files whose tool left the registry are
removed. Run after any registry edit or vendor reinstall:

    python3 scripts/build.py            # build
    python3 scripts/build.py --check    # exit 1 if anything on disk differs from what would be built
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import resolve as R  # noqa: E402

PLUGIN = R.PLUGIN_ROOT
COMMANDS = PLUGIN / "commands"
WIKI = PLUGIN / "wiki"
WIKI_TOOLS = WIKI / "tools"
WIKI_VENDORS = WIKI / "vendors"
REFS = PLUGIN / "skills" / "design-tools" / "references"
MARK = "<!-- GENERATED by scripts/build.py from registry/tools.json — edit the registry (or the installed SKILL.md), then rebuild. Do not edit this file. -->"
RESERVED = {"tool", "tools-list", "demo"}


def cmd_name(tool: str, meta: dict) -> str:
    """/design-tools:<vendor>-<tool>; no double prefix when the tool already carries the vendor key;
    `command` in the registry overrides."""
    if meta.get("command"):
        return meta["command"]
    v = meta["vendor"]
    if tool == v or tool.startswith(v + "-"):
        return tool
    return f"{v}-{tool}"


def description(tool: str, meta: dict, vendor: dict) -> str:
    writes = meta["mode"].startswith("W")
    tail = "Writes code." if writes and meta["class"] not in ("lookup", "judge") else "Read-only."
    if meta["mode"] == "W/R":
        tail = "Writes code in build mode; the audit mode is read-only."
    d = f"{vendor['display']} · {tool} — {meta['does']} {tail}"
    return d.replace('"', "'")


# ---------------------------------------------------------------- frontmatter -------------------

def parse_frontmatter(text: str) -> dict:
    """Tolerant YAML-subset parser: scalars, folded `>` scalars, `- item` lists, one level of nesting
    (kept as raw text under its key). Enough for SKILL.md frontmatter in the wild."""
    fm: dict = {}
    if not text.startswith("---"):
        return fm
    body = text.split("\n", 1)[1]
    end = body.find("\n---")
    if end < 0:
        return fm
    lines = body[:end].splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if not m:
            i += 1
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in (">", "|", ">-", "|-"):
            buf = []
            i += 1
            while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                buf.append(lines[i].strip())
                i += 1
            fm[key] = " ".join(b for b in buf if b) if val.startswith(">") else "\n".join(buf)
            continue
        if val == "":
            items, raw = [], []
            i += 1
            while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                s = lines[i].strip()
                raw.append(lines[i])
                if s.startswith("- "):
                    items.append(s[2:].strip().strip("\"'"))
                i += 1
            fm[key] = items if items else "\n".join(raw).strip()
            continue
        fm[key] = val.strip().strip("\"'").replace('\\"', '"') if not val.startswith("[") else val
        i += 1
    return fm


def skill_facts(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    fm = parse_frontmatter(text)
    d = path.parent
    refs = sorted(p.name for p in (d / "references").iterdir()) if (d / "references").is_dir() else []
    refs += sorted(p.name for p in (d / "reference").iterdir()) if (d / "reference").is_dir() else []
    scripts = sorted(p.name for p in (d / "scripts").iterdir()) if (d / "scripts").is_dir() else []
    other = sorted(p.name for p in d.iterdir() if p.name not in ("SKILL.md", "references", "reference", "scripts") and not p.name.startswith("."))
    return {
        "fm": fm,
        "lines": text.count("\n") + 1,
        "refs": refs,
        "scripts": scripts,
        "other": other,
        "base_note": "one lens of the broader `ui-craft` skill" in text,
    }


# ---------------------------------------------------------------- skill references -------------

def routing_phrases(tool: str, routing_md: str) -> list[str]:
    out = []
    for line in routing_md.splitlines():
        if not line.startswith("|") or line.startswith("|---") or "They say" in line:
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 2:
            continue
        if re.search(rf"`{re.escape(tool)}`", cells[1]):
            out.append(cells[0])
    return out


def collision_sections(tool: str, collisions_md: str) -> list[str]:
    out, current = [], None
    for line in collisions_md.splitlines():
        if line.startswith("## "):
            current = line[3:].strip()
        elif current and re.search(rf"`{re.escape(tool)}`", line) and current not in out:
            out.append(current)
    return out


def stacking_lines(tool: str, stacking_md: str) -> list[str]:
    return [l.strip("- ").strip() for l in stacking_md.splitlines()
            if l.startswith("- ") and re.search(rf"`{re.escape(tool)}`", l)]


# ---------------------------------------------------------------- templates ----------------------

CLASS_NOTES = {
    "orchestrator": (
        "**Orchestrator-class.** It takes art-direction decisions and wants a context of its own. "
        "Do not load a second orchestrator in this session. If the real ask is a whole new surface, "
        "`design-pipeline` runs it with gates and isolation — offer that before starting."
    ),
    "base": (
        "**The ui-craft base.** Loading it alone gives you the rules, the knobs and the Craft Report "
        "format; the lenses (`typeset`, `unhappy`, …) are the targeted passes on top of it."
    ),
    "preset": (
        "**A ui-craft preset** — the base with an aesthetic fixed. On a surface with a brand contract the "
        "contract owns the aesthetic; use the plain base or a lens instead."
    ),
    "phase": (
        "**A ui-craft phase command.** It is interactive by design — it will ask questions and wait. "
        "Answer them, or carry the answers in from the brief and the brand contract. `design-pipeline` "
        "wraps these as gates; calling one here is a deliberate single step, not a run."
    ),
    "modifier": (
        "**A modifier.** It changes how another tool writes; it does nothing on its own. Load it, then "
        "load the tool it modifies, and keep both in force for the whole write."
    ),
    "lookup": "**Lookup.** Answer, don't act. Change no files.",
    "judge": "**Judge.** Read-only by contract: report, score or verdict — change no files.",
    "technique": (
        "**Technique.** A framework- or effect-specific how-to. It assumes the motion or 3D decision "
        "is already made; if it is not, run the taste question through `/design-tools:discover` first."
    ),
    "pass": "",
}


def command_md(tool: str, meta: dict, vendor: dict, facts: dict | None) -> str:
    hint = (facts or {}).get("fm", {}).get("argument-hint") or "[target file, path or component] [notes]"
    writes = meta["mode"].startswith("W")
    desc = description(tool, meta, vendor)
    cmd = cmd_name(tool, meta)
    class_note = CLASS_NOTES.get(meta["class"], "")
    steps = [
        "1. **MISSING?** If the resolution block says `status: MISSING`, stop. Say where it looked and "
        f"point at `wiki/tools/{tool}.md` → *Install*. Do not improvise the pass from memory — that is "
        "exactly the failure this plugin exists to prevent.",
        f"2. **Load the tool.** `load: skill` → invoke `{tool}` with the Skill tool, passing the request. "
        "`load: read` → Read the `skill:` file"
        + (" — and the `base:` file **first**, it is a ui-craft lens —" if meta.get("base") else "")
        + " and follow it exactly as if it had been invoked with the request. Its relative "
        "`references/` resolve against `dir:`.",
    ]
    if writes:
        steps += [
            "3. **Brand contract.** Resolve `BRAND-CONTRACT.md` — working directory, then each parent. "
            "Its tokens, forbidden list, anti-slop laws and commerce laws outrank the vendor's opinion. "
            "If `.ui-craft/brief.md` exists, its §6 learned constraints apply too.",
            "4. **Read-only first** on code you have not seen this session: look before you write.",
            "5. **Run it** on the request. Stay inside this one tool — a second write-tool is a stacking "
            "question (`references/stacking.md`); a third is `design-pipeline`.",
            "6. **Report what changed**, one line per file.",
        ]
    else:
        steps += [
            "3. **Run it** on the request. This tool is read-only by contract: deliver the report, the "
            "score, the answer or the verdict — and change no files.",
            "4. If the report recommends a write pass, name the tool it maps to "
            "(`/design-tools:tools-list`) and stop; do not start it unasked.",
        ]
    return f"""---
description: "{desc}"
argument-hint: "{hint.replace('"', "'")}"
allowed-tools: Bash(bash ${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh:*), Bash(bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh":*), Bash(find:*), Read
---
{MARK}

# `{tool}` ({vendor['display']}) — direct engagement

`/design-tools:{cmd}` — you asked for **{tool}** by name, so `design-tools` is not routing — it is
loading. The guardrails still hold: read-only before write, the brand contract outranks
the vendor, say what changed. Reference card: `wiki/tools/{tool}.md` · vendor: `wiki/vendors/{meta['vendor']}.md`.
Whole-vendor entry point: `/design-tools:{meta['vendor']}`.

## Resolution

!`bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh" {tool}`

If the block above is empty or an error, the plugin root was not substituted. Find the resolver and
run it yourself with Bash:
`bash "$(find ~/.claude/plugins "$HOME/Library/Mobile Documents/com~apple~CloudDocs/alex.levnikov.root/claude_plugins" -path '*design-tools/scripts/resolve.sh' 2>/dev/null | head -1)" {tool}`

## Request

**$ARGUMENTS**

{class_note + chr(10) + chr(10) if class_note else ""}## Do

{chr(10).join(steps)}

**For:** {meta['for']}
**Not for:** {meta['not_for']}
"""


def vendor_command_md(vkey: str, vendor: dict, rows: list[dict], master_row: dict | None) -> str:
    tool_lines = "\n".join(
        f"- `/design-tools:{cmd_name(r['tool'], r['meta'])}` — {r['meta']['does']} "
        f"({'writes' if r['meta']['mode'].startswith('W') else 'read-only'})"
        for r in rows)
    desc_master = ""
    if master_row:
        m = master_row["meta"]; mt = master_row["tool"]
        hint = (master_row["facts"] or {}).get("fm", {}).get("argument-hint") or "[target] [notes]"
        desc = f"{vendor['display']} — vendor master: {mt}. {m['does']} Runs exactly as the vendor designed it."
        cn = CLASS_NOTES.get(m["class"], "")
        body = f"""# {vendor['display']} — vendor master: `{mt}`

`/design-tools:{vkey}` runs **{mt}**, the skill this vendor calls its entry point, **the way the vendor
designed it** — its own discovery questions, modes, knobs, argument format and report. The plugin's
guardrails (read-only first, one tool per step) are deliberately *not* layered on top: this command
exists precisely to let the vendor's own flow run. Two things still hold, because they are yours,
not the plugin's: `BRAND-CONTRACT.md` answers the vendor's brand and preference questions
(its tokens and forbidden list are the answer, not a suggestion), and you end by saying what changed,
one line per file.

## Resolution

!`bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh" {mt}`

If the block above is empty or an error, find the resolver and run it yourself:
`bash "$(find ~/.claude/plugins "$HOME/Library/Mobile Documents/com~apple~CloudDocs/alex.levnikov.root/claude_plugins" -path '*design-tools/scripts/resolve.sh' 2>/dev/null | head -1)" {mt}`

## Request — in the vendor's own format

Argument format: `{hint}`

**$ARGUMENTS**

## Do

1. `status: MISSING` → stop and say where it looked; do not improvise the vendor from memory.
2. Load it: `load: skill` → the Skill tool by name with the request; `load: read` → Read the `skill:`
   file (and `base:` first if printed) and follow it as if invoked. Relative `references/` and
   `scripts/` resolve against `dir:` — for vendors whose scripts assume a project-relative path,
   call them by that absolute `dir:`.
3. Resolve `BRAND-CONTRACT.md` (working directory, then parents) and hand it in wherever the vendor
   asks about brand, tokens, fonts, colours or preferences. If `.ui-craft/brief.md` exists, its §6
   applies too.
4. Follow the vendor's flow to its own end — its questions, its passes, its report. Do not
   substitute the plugin's steps. One constraint survives: **no second orchestrator-class skill in
   this context**; if the vendor's flow wants one, say so and stop.
5. Report what changed, one line per file.

{cn}

## This vendor's tools in the set

{tool_lines}

Vendor card: `wiki/vendors/{vkey}.md`.
"""
        return f"""---
description: "{desc.replace('"', "'")}"
argument-hint: "{hint.replace('"', "'")}"
allowed-tools: Bash(bash ${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh:*), Bash(bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh":*), Bash(find:*), Read
---
{MARK}

""" + body
    # hub — no master
    desc = f"{vendor['display']} — vendor hub: {len(rows)} tools ({', '.join(r['tool'] for r in rows[:6])}{'…' if len(rows) > 6 else ''}). Name one to run it, or list them."
    return f"""---
description: "{desc.replace('"', "'")}"
argument-hint: "[tool name from this vendor] [target]"
allowed-tools: Bash(bash ${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh:*), Bash(bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh":*), Bash(find:*), Read
---
{MARK}

# {vendor['display']} — vendor hub

This vendor has no single master skill; it ships {len(rows)} tools, each a command of its own.
`/design-tools:{vkey} <tool> <target>` runs that tool; `/design-tools:{vkey}` alone lists them.

**Request:** $ARGUMENTS

## Do

- If the request starts with one of the tool names below, run it exactly as its own command would
  (`commands/<command>.md`): resolve with `bash "${{CLAUDE_PLUGIN_ROOT}}/scripts/resolve.sh" <tool>`,
  load (`load: skill` → Skill tool; `load: read` → Read and follow, base first), brand contract before
  any write, run, report what changed. Read-only tools change nothing.
- If it names none of them, print the list below with one line each and ask which one — do not guess,
  and do not run two.

## Tools

{tool_lines}

Vendor card: `wiki/vendors/{vkey}.md` · vendor contract: {vendor.get('contract', '')}
"""


def tool_page(tool: str, meta: dict, vendor: dict, res: dict, facts: dict | None,
              phrases: list[str], collisions: list[str], stacks: list[str]) -> str:
    fm = (facts or {}).get("fm", {})
    lic = fm.get("license") or "not declared in SKILL.md — check the repo"
    ver = fm.get("version") or (fm.get("metadata") if isinstance(fm.get("metadata"), str) and "version" in fm.get("metadata", "") else None)
    flags = []
    if fm.get("user-invocable"):
        flags.append("`user-invocable: true`")
    if fm.get("disable-model-invocation"):
        flags.append("`disable-model-invocation: true` — runs only when named")
    if fm.get("allowed-tools"):
        at = fm["allowed-tools"]
        flags.append("`allowed-tools: " + (", ".join(at) if isinstance(at, list) else str(at)) + "`")
    routable = "yes — discovery proposes it freely" if meta["routable"] else "direct or whole-vendor only (`/design-tools:" + cmd_name(tool, meta) + "`)"
    where = res.get("skill", "—")
    found = res.get("found_in", "—")
    base_line = ""
    if meta.get("base"):
        base_line = f"\n**Base:** this is a `{meta['base']}` lens — the base loads first. → [{meta['base']}]({meta['base']}.md)\n"

    engage = [f"- Direct: `/design-tools:{cmd_name(tool, meta)} <target>`",
              f"- Vendor entry point: `/design-tools:{meta['vendor']}`"
              + (" — runs this very skill as the vendor's master" if vendor.get("master") == tool else
                 (f" — runs the vendor's master `{vendor['master']}`" if vendor.get("master") else " — lists the vendor's tools"))]
    if phrases:
        engage.append("- Discovery pre-rank: these phrasings (`references/phrases.md`) point here:")
        engage += [f"  - {p}" for p in phrases]
    elif meta["routable"]:
        engage.append("- Discovery: `/design-tools:discover <your words>` can propose it — no fixed phrasing recorded yet in `phrases.md`.")
    else:
        engage.append("- Discovery lists it only as a whole-vendor option, or when the request names it; the command above is the direct path.")

    def _cap(items: list[str], n: int = 20) -> str:
        shown = ", ".join(f"`{x}`" for x in items[:n])
        return shown + (f" … +{len(items) - n} more" if len(items) > n else "")

    files = [f"- `SKILL.md` — {facts['lines']} lines" if facts else "- `SKILL.md` — not resolved"]
    if facts and facts["refs"]:
        files.append(f"- `references/` ({len(facts['refs'])}) — " + _cap(facts["refs"]))
    if facts and facts["scripts"]:
        files.append(f"- `scripts/` ({len(facts['scripts'])}) — " + _cap(facts["scripts"]))
    if facts and facts["other"]:
        files.append("- also: " + ", ".join(f"`{o}`" for o in facts["other"]))

    xrefs = []
    if collisions:
        xrefs.append("**Collisions** (`references/collisions.md`): " + " · ".join(collisions))
    if stacks:
        xrefs.append("**Stacking** (`references/stacking.md`):\n" + "\n".join(f"- {s}" for s in stacks))

    desc = fm.get("description") or "_no description in frontmatter_"
    return f"""{MARK}

# `{tool}`

{meta['does']}

**Vendor:** [{vendor.get('display', meta['vendor'])}](../vendors/{meta['vendor']}.md) · {vendor.get('repo')}
**Mode:** {meta['mode']} · **Class:** {meta['class']} · **Group:** {meta['group']} · **Routable:** {routable}
{base_line}
**For:** {meta['for']}
**Not for:** {meta['not_for']}

## Engage

{chr(10).join(engage)}

## What the vendor says

> {desc}

| | |
|---|---|
| `name` | `{fm.get('name', tool)}` |
| version | {ver or '—'} |
| license | {lic} |
| argument-hint | {('`' + str(fm.get('argument-hint')) + '`') if fm.get('argument-hint') else '—'} |
| flags | {'; '.join(flags) if flags else '—'} |

## Files

{chr(10).join(files)}

## Where it lives

- Resolved from: `{found}`
- Path: `{where}`
- Install / refresh: `{vendor.get('install', 'see repo')}`
- Any project: `bash design-studio/scripts/skillset.sh install <set> <project>` copies it into `<project>/.claude/skills/`, after which the Skill tool sees it by name.

{chr(10).join(xrefs) if xrefs else ''}
"""


def readme(reg: dict, rows: list[dict]) -> str:
    vendors = reg["vendors"]
    by_vendor: dict[str, list[dict]] = {}
    for r in rows:
        by_vendor.setdefault(r["meta"]["vendor"], []).append(r)
    vlines = ["| Vendor | Entry command | Master skill | Tools | Page |", "|---|---|---|---|---|"]
    for vk, v in vendors.items():
        ts = by_vendor.get(vk, [])
        vlines.append(f"| **{v['display']}** · {v['repo']} | `/design-tools:{vk}` | {('`' + v['master'] + '` — runs as designed') if v.get('master') else 'none — hub lists tools'} | {len(ts)} | [vendors/{vk}.md](vendors/{vk}.md) |")
    clines = []
    for vk, v in vendors.items():
        ts = by_vendor.get(vk, [])
        clines.append(f"\n**{v['display']}** — `/design-tools:{vk}`"
                      + (f" runs `{v['master']}` as the vendor designed it" if v.get("master") else " lists and dispatches"))
        for r in ts:
            clines.append(f"- `/design-tools:{cmd_name(r['tool'], r['meta'])}` — {r['meta']['does']}")

    glines = []
    for gk, gtitle in reg["groups"].items():
        rs = [r for r in rows if r["meta"]["group"] == gk]
        if not rs:
            continue
        glines.append(f"\n### {gtitle}\n")
        glines.append("| Tool | Vendor | Mode | Class | Routable | What it does |")
        glines.append("|---|---|---|---|---|---|")
        for r in rs:
            m = r["meta"]
            glines.append(f"| [`{r['tool']}`](tools/{r['tool']}.md) | {m['vendor']} | {m['mode']} | {m['class']} | {'yes' if m['routable'] else 'no'} | {m['does']} |")

    missing = [r["tool"] for r in rows if r["res"]["status"] != "OK"]
    health = (f"{len(rows) - len(missing)}/{len(rows)} tools resolved at build time"
              + (f"; **MISSING:** {', '.join(missing)}" if missing else "; nothing missing."))
    roots = "\n".join(f"- `{r['name']}` → `{r['path']}` — {r.get('note', '')}" for r in reg["roots"])
    return f"""{MARK}

# design-tools wiki

Every vendor and every tool in the set, how each is engaged, and where it actually lives.
`/design-tools:discover <task>` runs a request through all of them and lets you pick; the per-tool
commands (`/design-tools:<vendor>-<tool>`) engage one by name; `/design-tools:<vendor>` runs a vendor's
master as designed. All load a tool the same way — see [LOADING.md](LOADING.md).

## How a tool is loaded

1. The tool is chosen — picked from discovery's list, or named by you.
2. `scripts/resolve.sh <tool>` finds its `SKILL.md`: project `.claude/skills` → `~/.claude/skills` →
   configured roots → the registry roots below.
3. `load: skill` (found in project/user scope) → the Skill tool by name. `load: read` (found in a
   root) → the file is read and followed as if invoked; ui-craft lenses load their base first.

Registry roots:
{roots}

Health: {health}

## Vendors

{chr(10).join(vlines)}

## Tools by group
{chr(10).join(glines)}

## Commands, grouped by vendor
{chr(10).join(clines)}

## Other commands

- `/design-tools:discover <task in your words>` — the front door: candidates → you pick → a prompt is
  written to `.design-tools/<slug>.prompt.md` → run now or later.
- `/design-tools:run [file]` — execute a written prompt, loading the tools exactly as it says.
- `/design-tools:tools-list [group]` — print the catalog, change nothing.
- `/design-tools:<vendor>` — the vendor's entry point: runs its master skill exactly as the vendor
  designed it (ui-craft, impeccable, taste → design-taste-frontend, …), or lists the vendor's tools
  when it has no master (emil, osmani, ibelick, iart, threejs).
- `/design-tools:<vendor>-<tool> <target>` — engage one tool by name, skipping discovery. Names are
  vendor-prefixed so the picker groups them: type `/design-tools:ui-craft` to see every ui-craft lens.
  One command per tool ({len(rows)} in total) plus one per vendor, regenerated by `python3 scripts/build.py`.
- `/design-tools:demo [tool]` — open the design-studio dashboard (or one tool's bake-off demo) in the
  browser, if it exists on this machine. Read-only; `scripts/dashboard.sh`.
"""


# ---------------------------------------------------------------- main ------------------------

def build(check: bool) -> int:
    reg = R.load_registry()
    routing_md = (REFS / "phrases.md").read_text(encoding="utf-8")
    collisions_md = (REFS / "collisions.md").read_text(encoding="utf-8")
    stacking_md = (REFS / "stacking.md").read_text(encoding="utf-8")

    rows = []
    for tool, meta in reg["tools"].items():
        if tool in RESERVED:
            print(f"✖ tool name {tool!r} collides with a hand-written command; rename it", file=sys.stderr)
            return 2
        res = R.resolve(tool, reg)
        facts = skill_facts(Path(res["skill"])) if res["status"] == "OK" else None
        vendor = reg["vendors"][meta["vendor"]]
        rows.append({
            "tool": tool, "meta": meta, "res": res, "facts": facts, "vendor": vendor,
            "phrases": routing_phrases(tool, routing_md),
            "collisions": collision_sections(tool, collisions_md),
            "stacks": stacking_lines(tool, stacking_md),
        })

    planned: dict[Path, str] = {}
    seen_cmd: dict[str, str] = {}
    for r in rows:
        c = cmd_name(r["tool"], r["meta"])
        if c in RESERVED or c in seen_cmd:
            print(f"✖ command name collision: {c!r} ({r['tool']} vs {seen_cmd.get(c, 'reserved')})", file=sys.stderr)
            return 2
        seen_cmd[c] = r["tool"]
        planned[COMMANDS / f"{c}.md"] = command_md(r["tool"], r["meta"], r["vendor"], r["facts"])
        planned[WIKI_TOOLS / f"{r['tool']}.md"] = tool_page(
            r["tool"], r["meta"], r["vendor"], r["res"], r["facts"], r["phrases"], r["collisions"], r["stacks"])
    # one entry command per vendor — master (runs the vendor's own skill as designed) or hub
    by_vendor: dict[str, list[dict]] = {}
    for r in rows:
        by_vendor.setdefault(r["meta"]["vendor"], []).append(r)
    for vk, v in reg["vendors"].items():
        vrows = by_vendor.get(vk, [])
        master_row = next((r for r in vrows if r["tool"] == v.get("master")), None)
        if v.get("master") and master_row is None:
            print(f"✖ vendor {vk!r} names master {v['master']!r} which is not a registered tool", file=sys.stderr)
            return 2
        if vk in RESERVED:
            print(f"✖ vendor key {vk!r} collides with a hand-written command", file=sys.stderr)
            return 2
        # a master whose own command name equals the vendor key (ui-craft, impeccable, …) is replaced by the vendor command
        planned[COMMANDS / f"{vk}.md"] = vendor_command_md(vk, v, vrows, master_row)
    planned[WIKI / "README.md"] = readme(reg, rows)

    # stale generated files
    stale = []
    for d in (COMMANDS, WIKI_TOOLS):
        if d.is_dir():
            for f in d.glob("*.md"):
                if f not in planned and MARK in f.read_text(encoding="utf-8", errors="replace"):
                    stale.append(f)

    if check:
        diffs = [p for p, c in planned.items() if not p.is_file() or p.read_text(encoding="utf-8") != c]
        for p in diffs:
            print(f"✖ out of date: {p.relative_to(PLUGIN)}")
        for f in stale:
            print(f"✖ stale generated file: {f.relative_to(PLUGIN)}")
        missing = [r["tool"] for r in rows if r["res"]["status"] != "OK"]
        if missing:
            print(f"⚠ unresolved at check time: {', '.join(missing)}")
        if diffs or stale:
            return 1
        print(f"✔ {len(planned)} generated files are current; {len(rows)} tools; "
              f"{len(rows) - len(missing)} resolved")
        return 0

    for d in (COMMANDS, WIKI_TOOLS, WIKI_VENDORS):
        d.mkdir(parents=True, exist_ok=True)
    for p, c in planned.items():
        p.write_text(c, encoding="utf-8")
    for f in stale:
        f.unlink()
        print(f"– removed stale {f.relative_to(PLUGIN)}")
    vendor_pages_missing = [vk for vk in reg["vendors"] if not (WIKI_VENDORS / f"{vk}.md").is_file()]
    missing = [r["tool"] for r in rows if r["res"]["status"] != "OK"]
    ncmd = sum(1 for p in planned if p.parent == COMMANDS)
    print(f"✔ wrote {len(planned)} files: {ncmd} commands ({len(rows)} tools + {len(reg['vendors'])} vendors, merged where equal), {len(rows)} tool pages, README")
    print(f"  resolved {len(rows) - len(missing)}/{len(rows)}" + (f"; MISSING: {', '.join(missing)}" if missing else ""))
    if vendor_pages_missing:
        print(f"  ⚠ hand-written vendor pages missing: {', '.join(vendor_pages_missing)}")
    return 0


if __name__ == "__main__":
    sys.exit(build(check="--check" in sys.argv))
